### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by BirmacherAkos**

### CODE REVIEW

**Comment by Helfoar** [comment]
T

**Comment by Helfoar** [comment]
ttt

**Comment by BirmacherAkos** [comment]
T2

**Comment by Helfoar** [comment]
T22

**Comment by Helfoar** [comment]
[ ]

**Comment by Helfoar** [comment]
`### Solar System Exploration, 1950s – 1960s

- [ ] Mercury
- [x] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
- [ ] Neptune
- [ ] Comet Haley`

**Comment by Helfoar** [comment]
aaa

**Pull request closed without merging**
